export default {
  TOGGLE_DATA_LOADING: 'TOGGLE_DATA_LOADING',
  FETCH_API_START: 'FETCH_API_START',
  FETCH_API_SUCCESS: 'FETCH_API_SUCCESS',
  FETCH_API_FAILURE: 'FETCH_API_FAILURE',
  SET_GNOME_NAME_SEARCHFIELD: 'SET_GNOME_NAME_SEARCHFIELD',
  SET_PROFESSION_SEARCHFIELD: 'SET_PROFESSION_SEARCHFIELD',
};
